all: p1 p2 p3 p4 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8

clean:
	rm -f p1 p2 p3 p4 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8
 
p1: p1.c
	gcc -o p1 p1.c -Wall

p2: p2.c
	gcc -o p2 p2.c -Wall

p3: p3.c
	gcc -o p3 p3.c -Wall

p4: p4.c
	gcc -o p4 p4.c -Wall

Q1: Q1.c
	gcc -o Q1 Q1.c -Wall

Q2: Q2.c
	gcc -o Q2 Q2.c -Wall

Q3: Q3.c
	gcc -o Q3 Q3.c -Wall

Q4: Q4.c
	gcc -o Q4 Q4.c -Wall

Q5: Q5.c
	gcc -o Q5 Q5.c -Wall

Q6: Q6.c
	gcc -o Q6 Q6.c -Wall

Q7: Q7.c
	gcc -o Q7 Q7.c -Wall

Q8: Q8.c
	gcc -o Q8 Q8.c -Wall